-- =====================================================
-- ADD 50+ PROFESSIONAL NUTRITION RESOURCES
-- =====================================================

-- Insert comprehensive nutrition resources
INSERT INTO educational_resources (title, description, content, resource_type, category, tags, is_public, view_count) VALUES

-- NUTRITION BASICS (10 resources)
('Understanding Macronutrients', 'Complete guide to proteins, carbohydrates, and fats and their role in a balanced diet.', 'Macronutrients are the nutrients your body needs in large amounts: proteins, carbohydrates, and fats. Proteins build and repair tissues, carbs provide energy, and fats support cell function and hormone production. A balanced diet typically includes 45-65% carbs, 10-35% protein, and 20-35% fats.', 'article', 'nutrition', ARRAY['macronutrients', 'nutrition basics', 'diet planning'], true, 0),

('Micronutrients: Vitamins and Minerals Guide', 'Essential vitamins and minerals your body needs for optimal health.', 'Vitamins and minerals are essential micronutrients needed in small amounts. Key vitamins include A, B-complex, C, D, E, and K. Important minerals include calcium, iron, magnesium, potassium, and zinc. Each plays a unique role in body functions.', 'article', 'nutrition', ARRAY['vitamins', 'minerals', 'micronutrients', 'health'], true, 0),

('Hydration 101: Water and Electrolytes', 'Learn why proper hydration is crucial and how to maintain electrolyte balance.', 'Proper hydration is essential for all body functions. Aim for 8-10 glasses daily, more during exercise. Electrolytes (sodium, potassium, magnesium) help maintain fluid balance. Signs of dehydration include dark urine, fatigue, and headaches.', 'article', 'nutrition', ARRAY['hydration', 'water', 'electrolytes', 'wellness'], true, 0),

('Reading Nutrition Labels Like a Pro', 'Master the art of understanding food labels and making informed choices.', 'Nutrition labels provide crucial information. Check serving size first, then calories, and focus on limiting saturated fat, sodium, and added sugars. Look for high fiber, protein, vitamins, and minerals. Pay attention to ingredient lists - items are listed by weight.', 'article', 'nutrition', ARRAY['nutrition labels', 'food labels', 'healthy eating'], true, 0),

('Glycemic Index and Blood Sugar Management', 'Understanding how foods affect blood sugar levels.', 'The Glycemic Index (GI) ranks carbohydrates by how quickly they raise blood sugar. Low GI foods (55 or less) include most fruits, vegetables, and whole grains. High GI foods (70+) include white bread and sugary snacks. Choose low-GI foods for sustained energy.', 'article', 'nutrition', ARRAY['glycemic index', 'blood sugar', 'diabetes', 'carbohydrates'], true, 0),

('Fiber: The Unsung Hero of Nutrition', 'Why fiber is essential and how to get more in your diet.', 'Fiber aids digestion, controls blood sugar, and promotes heart health. Adults need 25-38g daily. Soluble fiber (oats, beans) lowers cholesterol. Insoluble fiber (whole grains, vegetables) promotes regularity. Gradually increase fiber intake with plenty of water.', 'article', 'nutrition', ARRAY['fiber', 'digestion', 'gut health', 'whole grains'], true, 0),

('Protein Power: Complete vs Incomplete Proteins', 'Learn the difference between protein sources and how to optimize intake.', 'Complete proteins contain all 9 essential amino acids and include meat, fish, eggs, and dairy. Incomplete proteins (beans, nuts, grains) can be combined to form complete proteins. Aim for 0.8-1g protein per kg body weight daily.', 'article', 'nutrition', ARRAY['protein', 'amino acids', 'muscle building', 'vegetarian'], true, 0),

('Healthy Fats vs Unhealthy Fats', 'Navigate the world of dietary fats and make heart-healthy choices.', 'Healthy fats (monounsaturated and polyunsaturated) include olive oil, avocados, nuts, and fatty fish. They support brain function and reduce inflammation. Limit saturated fats (butter, red meat) and avoid trans fats. Omega-3 fatty acids are particularly beneficial.', 'article', 'nutrition', ARRAY['fats', 'healthy fats', 'omega-3', 'heart health'], true, 0),

('Antioxidants and Free Radicals', 'Understand oxidative stress and how antioxidants protect your body.', 'Free radicals cause oxidative stress, leading to cell damage and aging. Antioxidants neutralize free radicals. Key antioxidants include vitamins C and E, beta-carotene, and selenium. Find them in berries, dark chocolate, nuts, and colorful vegetables.', 'article', 'nutrition', ARRAY['antioxidants', 'free radicals', 'aging', 'immunity'], true, 0),

('Probiotics and Gut Health', 'The importance of gut microbiome and probiotic-rich foods.', 'A healthy gut microbiome supports digestion, immunity, and mental health. Probiotics are beneficial bacteria found in yogurt, kefir, sauerkraut, and kimchi. Prebiotics (fiber-rich foods) feed good bacteria. Aim for diverse probiotic sources daily.', 'article', 'nutrition', ARRAY['probiotics', 'gut health', 'microbiome', 'digestion'], true, 0),

-- WEIGHT MANAGEMENT (10 resources)
('Sustainable Weight Loss: Science-Based Strategies', 'Evidence-based approaches to healthy, lasting weight loss.', 'Sustainable weight loss requires a 500-750 calorie daily deficit for 1-2 lbs/week loss. Focus on whole foods, regular exercise, adequate sleep, and stress management. Avoid fad diets. Small, consistent changes lead to long-term success.', 'article', 'weight_loss', ARRAY['weight loss', 'calorie deficit', 'sustainable', 'healthy habits'], true, 0),

('Metabolism Myths and Facts', 'Debunking common myths about metabolism and weight.', 'Metabolism varies by age, genetics, and muscle mass. While you can''t drastically "boost" metabolism, building muscle, staying active, eating enough protein, and avoiding crash diets help maintain metabolic rate. Yo-yo dieting can slow metabolism over time.', 'article', 'weight_loss', ARRAY['metabolism', 'weight loss myths', 'fat burning'], true, 0),

('Portion Control Without Measuring', 'Visual guides and practical tips for managing portion sizes.', 'Use the plate method: half vegetables, quarter protein, quarter carbs. Hand portions: palm-sized protein, fist-sized carbs, thumb-sized fats, handful of snacks. Eat slowly, use smaller plates, and stop when 80% full to prevent overeating.', 'article', 'weight_loss', ARRAY['portion control', 'mindful eating', 'weight management'], true, 0),

('Emotional Eating: Strategies and Solutions', 'Understanding and overcoming emotional eating patterns.', 'Emotional eating is using food to cope with feelings rather than hunger. Identify triggers (stress, boredom, sadness). Find alternatives: exercise, journaling, calling friends. Practice mindful eating. Keep a food-mood journal to recognize patterns.', 'article', 'wellness', ARRAY['emotional eating', 'mindfulness', 'mental health', 'habits'], true, 0),

('Intermittent Fasting: A Complete Guide', 'Understanding different IF protocols and their benefits.', 'Intermittent fasting alternates eating and fasting periods. Common methods: 16:8 (16-hour fast, 8-hour eating window), 5:2 (normal eating 5 days, 500-600 calories 2 days). Benefits include improved insulin sensitivity and cellular repair. Not suitable for everyone.', 'article', 'weight_loss', ARRAY['intermittent fasting', 'fasting', 'weight loss', 'insulin'], true, 0),

('Building a Healthy Relationship with Food', 'Move beyond dieting to intuitive, joyful eating.', 'Reject diet mentality. Honor hunger and fullness cues. Make peace with all foods - no "good" or "bad" labels. Challenge food thoughts. Respect your body. Practice gentle nutrition. Food is fuel and pleasure, not punishment or reward.', 'article', 'wellness', ARRAY['intuitive eating', 'food relationship', 'body positivity', 'mindfulness'], true, 0),

('Plateaus: Why They Happen and How to Break Through', 'Overcoming weight loss plateaus with science-backed strategies.', 'Plateaus occur as your body adapts. Strategies: reassess calories, vary workouts, increase protein, manage stress, prioritize sleep, track non-scale victories. Be patient - plateaus are normal. Focus on health, not just weight.', 'article', 'weight_loss', ARRAY['weight loss plateau', 'fitness', 'motivation'], true, 0),

('Strength Training for Fat Loss', 'Why lifting weights is essential for weight management.', 'Strength training builds muscle, which burns more calories at rest. It preserves muscle during weight loss, improves body composition, boosts metabolism, and strengthens bones. Aim for 2-3 sessions weekly, focusing on compound movements.', 'article', 'exercise', ARRAY['strength training', 'fat loss', 'muscle building', 'metabolism'], true, 0),

('The Role of Sleep in Weight Management', 'How quality sleep impacts hunger, metabolism, and weight.', 'Poor sleep disrupts hormones: increases ghrelin (hunger hormone), decreases leptin (satiety hormone), and elevates cortisol (stress hormone). Aim for 7-9 hours nightly. Sleep deprivation leads to cravings, poor food choices, and weight gain.', 'article', 'wellness', ARRAY['sleep', 'weight management', 'hormones', 'health'], true, 0),

('Stress, Cortisol, and Weight Gain', 'Understanding the stress-weight connection and solutions.', 'Chronic stress elevates cortisol, promoting fat storage (especially belly fat), increasing cravings, and disrupting sleep. Manage stress through exercise, meditation, deep breathing, adequate sleep, and social connection. Chronic stress sabotages weight loss efforts.', 'article', 'wellness', ARRAY['stress management', 'cortisol', 'weight gain', 'mental health'], true, 0),

-- MEAL PLANNING & PREP (10 resources)
('Meal Prep 101: Beginner''s Guide', 'Start meal prepping with these simple, time-saving strategies.', 'Choose one day weekly for prep. Start simple: batch cook proteins, chop vegetables, prep 3-4 meals. Invest in quality containers. Use versatile ingredients. Theme days simplify planning (Meatless Monday, Taco Tuesday). Start with 2-3 meals, then expand.', 'article', 'meal_prep', ARRAY['meal prep', 'meal planning', 'time management', 'cooking'], true, 0),

('Batch Cooking Mastery', 'Efficient techniques for cooking multiple meals at once.', 'Cook large batches of grains, proteins, and roasted vegetables. Use slow cookers and sheet pans. Double recipes and freeze portions. Prep ingredients Sunday, cook Monday. One-pot meals save time and dishes. Label and date all containers.', 'article', 'meal_prep', ARRAY['batch cooking', 'meal prep', 'efficiency', 'freezer meals'], true, 0),

('Budget-Friendly Healthy Eating', 'Eat nutritiously without breaking the bank.', 'Buy seasonal produce, use frozen vegetables, buy generic brands, plan meals around sales, use dried beans and lentils, minimize food waste, buy in bulk, grow herbs, make meals from scratch, and shop with a list to avoid impulse purchases.', 'article', 'recipes', ARRAY['budget meals', 'frugal', 'meal planning', 'savings'], true, 0),

('Building a Balanced Plate', 'Create nutritionally complete meals every time.', 'Follow the plate method: 50% non-starchy vegetables, 25% lean protein, 25% complex carbs, plus healthy fat. Include variety in colors for diverse nutrients. Add herbs and spices for flavor without calories. Adjust portions based on activity level.', 'article', 'nutrition', ARRAY['balanced diet', 'meal planning', 'nutrition'], true, 0),

('Pantry Staples for Healthy Cooking', 'Essential ingredients every kitchen should have.', 'Stock: whole grains (quinoa, brown rice, oats), canned beans, canned tomatoes, olive oil, vinegar, herbs/spices, nuts, seeds, nut butters, low-sodium broth, whole grain pasta. These provide quick, nutritious meals anytime.', 'article', 'meal_prep', ARRAY['pantry staples', 'grocery shopping', 'meal planning'], true, 0),

('5 Quick Breakfasts Under 10 Minutes', 'Nutritious morning meals for busy schedules.', '1) Overnight oats with berries and nuts, 2) Greek yogurt parfait with granola and fruit, 3) Whole grain toast with avocado and egg, 4) Smoothie with protein powder and greens, 5) Egg muffins prepped ahead. All balanced and energizing.', 'article', 'recipes', ARRAY['breakfast', 'quick meals', 'meal prep', 'morning'], true, 0),

('Make-Ahead Lunch Ideas', '15 nutritious lunches you can prepare in advance.', 'Buddha bowls, mason jar salads, wraps, grain bowls, soup and salad combos, bento boxes, sandwich prep, leftover transformations. Keep dressings separate. Include protein, complex carbs, vegetables, and healthy fats for satisfaction.', 'article', 'recipes', ARRAY['lunch', 'meal prep', 'work meals', 'portable meals'], true, 0),

('Dinner in 30 Minutes or Less', 'Fast, healthy dinner solutions for weeknights.', 'Sheet pan meals, stir-fries, one-pot pastas, grain bowls, tacos, quick curries. Keep pre-chopped vegetables, cooked grains, and rotisserie chicken on hand. Use high-quality shortcuts strategically. Simplicity doesn''t mean sacrificing nutrition.', 'article', 'recipes', ARRAY['dinner', 'quick meals', 'weeknight dinners', '30-minute meals'], true, 0),

('Snack Smart: Healthy Options for Any Time', '25 nutritious snacks that satisfy and nourish.', 'Protein-rich snacks: nuts, Greek yogurt, cheese, hummus. Fiber-rich: fruit with nut butter, vegetables with dip, whole grain crackers. Combo snacks: trail mix, energy balls, protein smoothies. Aim for 150-200 calories with protein and fiber.', 'article', 'nutrition', ARRAY['snacks', 'healthy snacks', 'portable snacks', 'protein'], true, 0),

('Freezer-Friendly Meals Guide', 'Foods that freeze well and reheating tips.', 'Freeze well: soups, stews, casseroles, cooked grains, cooked beans, meatballs, burgers, sauces. Don''t freeze: lettuce, raw potatoes, cream-based sauces, fried foods. Cool completely before freezing. Use within 3 months for best quality. Label with date and contents.', 'article', 'meal_prep', ARRAY['freezer meals', 'meal prep', 'food storage'], true, 0),

-- SPECIAL DIETS (10 resources)
('Plant-Based Nutrition Essentials', 'Thriving on a vegetarian or vegan diet.', 'Focus on protein sources: legumes, tofu, tempeh, nuts, seeds. Ensure B12 supplementation. Combine grains and legumes for complete proteins. Include iron-rich foods with vitamin C. Get omega-3s from flax, chia, walnuts. Plan meals for adequate calories and nutrients.', 'article', 'nutrition', ARRAY['plant-based', 'vegan', 'vegetarian', 'protein'], true, 0),

('Low-Carb and Keto Diets Explained', 'Understanding ketogenic and low-carb approaches.', 'Keto: under 50g carbs daily, entering ketosis. Low-carb: 50-150g carbs daily. Benefits include appetite control and stable blood sugar. Challenges: initial adaptation, nutrient deficiencies, sustainability. Not suitable for everyone. Focus on quality fats and adequate protein.', 'article', 'nutrition', ARRAY['keto', 'low-carb', 'ketosis', 'diet'], true, 0),

('Mediterranean Diet: A Lifestyle Approach', 'The heart-healthy diet backed by decades of research.', 'Emphasizes olive oil, fish, vegetables, fruits, whole grains, legumes, nuts. Moderate wine, limited red meat and sweets. Benefits: reduced heart disease, diabetes, cognitive decline. It''s not just food - includes physical activity and social meals.', 'article', 'nutrition', ARRAY['Mediterranean diet', 'heart health', 'longevity', 'lifestyle'], true, 0),

('DASH Diet for Blood Pressure Management', 'Dietary approaches to stop hypertension naturally.', 'Focus on vegetables, fruits, whole grains, lean proteins, low-fat dairy. Limit sodium to 1500-2300mg daily. Emphasize potassium, calcium, magnesium. Reduce processed foods. Studies show significant blood pressure reductions within weeks.', 'article', 'nutrition', ARRAY['DASH diet', 'blood pressure', 'hypertension', 'heart health'], true, 0),

('Gluten-Free Living: Beyond the Basics', 'Navigating a gluten-free diet safely and deliciously.', 'Avoid wheat, barley, rye. Safe grains: rice, quinoa, corn, oats (certified GF). Check labels for hidden gluten. Watch for cross-contamination. Focus on naturally GF whole foods. Ensure adequate fiber and B vitamins. Celiac disease requires strict adherence.', 'article', 'nutrition', ARRAY['gluten-free', 'celiac', 'food allergies', 'diet'], true, 0),

('Managing Food Allergies and Intolerances', 'Strategies for identifying and avoiding trigger foods.', 'Common allergens: milk, eggs, peanuts, tree nuts, soy, wheat, fish, shellfish. Keep detailed food diary. Learn to read labels carefully. Find substitutions. Carry emergency medication if needed. Work with allergist and dietitian for proper management.', 'article', 'nutrition', ARRAY['food allergies', 'intolerances', 'elimination diet', 'safety'], true, 0),

('Anti-Inflammatory Diet Guide', 'Reduce chronic inflammation through food choices.', 'Emphasize: fatty fish, olive oil, berries, leafy greens, nuts, tomatoes, turmeric, ginger. Limit: processed foods, refined carbs, excess sugar, fried foods, red meat. Benefits include reduced chronic disease risk and improved recovery from exercise.', 'article', 'nutrition', ARRAY['anti-inflammatory', 'chronic disease', 'inflammation', 'health'], true, 0),

('Diabetic Diet Management', 'Blood sugar control through strategic eating.', 'Focus on consistent carb intake, pair carbs with protein/fat, choose low-GI foods, eat regular meals. Monitor portions, limit added sugars and refined carbs. Include fiber-rich foods. Work with healthcare team for individualized plan and medication timing.', 'article', 'nutrition', ARRAY['diabetes', 'blood sugar', 'diabetic diet', 'health condition'], true, 0),

('Heart-Healthy Eating Plan', 'Nutrition strategies to support cardiovascular health.', 'Emphasize: fish, nuts, olive oil, whole grains, fruits, vegetables. Limit saturated fat, trans fats, sodium, added sugars. Include omega-3s regularly. Control portions. Maintain healthy weight. Combine with exercise and stress management for maximum benefit.', 'article', 'nutrition', ARRAY['heart health', 'cardiovascular', 'cholesterol', 'heart disease'], true, 0),

('Nutrition for Athletic Performance', 'Fueling training, competition, and recovery.', 'Pre-workout: carbs and moderate protein 2-3 hours before. During: simple carbs and electrolytes for sessions over 60 minutes. Post-workout: carbs and protein within 30-60 minutes. Stay hydrated. Increase overall calories to match training volume.', 'article', 'exercise', ARRAY['sports nutrition', 'athletic performance', 'workout nutrition', 'recovery'], true, 0),

-- RECIPES & COOKING (10 resources)
('10 High-Protein Vegetarian Meals', 'Delicious meatless meals packed with protein.', '1) Lentil bolognese, 2) Chickpea curry, 3) Black bean burgers, 4) Tofu stir-fry, 5) Quinoa stuffed peppers, 6) White bean chili, 7) Tempeh tacos, 8) Greek-style baked eggs, 9) Edamame pasta, 10) Peanut noodles. Each provides 20+ grams protein per serving.', 'article', 'recipes', ARRAY['vegetarian', 'high protein', 'plant-based', 'recipes'], true, 0),

('Smoothie Bowls: 15 Nutrient-Dense Recipes', 'Thick, spoonable smoothies topped with superfoods.', 'Base: frozen fruit, liquid, protein source. Popular: Acai berry, green detox, chocolate peanut butter, tropical mango. Toppings: granola, nuts, seeds, coconut, fresh fruit. Make ahead smoothie packs for convenience. Perfect for quick, customizable meals.', 'article', 'recipes', ARRAY['smoothie bowls', 'breakfast', 'healthy recipes', 'superfoods'], true, 0),

('One-Pot Wonders: 20 Easy Meals', 'Minimal cleanup, maximum flavor and nutrition.', 'Pasta primavera, chicken and rice, beef stew, vegetable curry, jambalaya, minestrone soup, chili, paella, risotto, quinoa bowl. Use Dutch oven, slow cooker, or instant pot. Layer flavors, include vegetables, balance macronutrients.', 'article', 'recipes', ARRAY['one-pot meals', 'easy cooking', 'minimal cleanup', 'dinner'], true, 0),

('Sheet Pan Dinners: 15 Complete Meals', 'Everything cooks together for easy weeknight dinners.', 'Chicken fajitas, salmon and vegetables, sausage and potatoes, Mediterranean chicken, beef and broccoli, pork chops with apples, shrimp and asparagus. Arrange strategically, consider cooking times, use parchment for easy cleanup. 400-425°F for most recipes.', 'article', 'recipes', ARRAY['sheet pan meals', 'easy dinners', 'one pan', 'roasting'], true, 0),

('Mason Jar Salads: 12 Fresh Ideas', 'Layered salads that stay crisp all week.', 'Layer order (bottom to top): dressing, sturdy vegetables, grains/protein, delicate greens, toppings. Ideas: Greek, taco, Asian sesame, Cobb, Mediterranean. Prep Sunday, eat through Thursday. Shake before eating. Use wide-mouth quart jars.', 'article', 'recipes', ARRAY['mason jar salads', 'meal prep', 'salads', 'lunch'], true, 0),

('Healthy Desserts: Satisfy Your Sweet Tooth', '25 treats that won''t derail your goals.', 'Fruit-based: nice cream, grilled peaches, berry parfaits. Chocolate: avocado mousse, protein brownies, dark chocolate bark. Energy balls, chia pudding, yogurt bark, baked apples. Use natural sweeteners, include protein/healthy fats, watch portions.', 'article', 'recipes', ARRAY['healthy desserts', 'sweets', 'treats', 'sugar alternatives'], true, 0),

('Soup Recipes for Every Season', '20 nourishing soups from light to hearty.', 'Spring: pea, asparagus. Summer: gazpacho, corn chowder. Fall: butternut squash, minestrone. Winter: lentil, chicken noodle, beef stew. Techniques: roast vegetables first for depth, blend for creaminess, freeze individual portions, add fresh herbs at end.', 'article', 'recipes', ARRAY['soups', 'comfort food', 'seasonal cooking', 'meal prep'], true, 0),

('Breakfast Meal Prep: 10 Make-Ahead Options', 'Start your day right with prepped breakfasts.', 'Overnight oats variations, egg muffin cups, breakfast burritos, chia pudding, granola, breakfast cookies, frittata slices, yogurt parfait jars, baked oatmeal, protein pancakes. Most last 3-5 days refrigerated or freeze for longer storage.', 'article', 'recipes', ARRAY['breakfast', 'meal prep', 'make-ahead', 'morning meals'], true, 0),

('Buddha Bowls: 15 Balanced Bowl Recipes', 'Complete meals in a bowl with perfect balance.', 'Base: grain or greens. Add: protein, roasted vegetables, raw vegetables, healthy fat, sauce. Popular: Mediterranean, Mexican, Asian, Greek. Customize to preferences. Use leftovers creatively. Prep components ahead. Nutrition and flavor in every bite.', 'article', 'recipes', ARRAY['buddha bowls', 'grain bowls', 'balanced meals', 'lunch'], true, 0),

('Cooking Methods for Maximum Nutrition', 'Preserve nutrients while creating delicious meals.', 'Steam vegetables to retain vitamins. Roast for caramelization without added fat. Grill for flavor. Sauté quickly over high heat. Avoid: boiling vegetables extensively, overcooking, excess oil. Raw vs cooked: some nutrients increase (lycopene) while others decrease (vitamin C).', 'article', 'nutrition', ARRAY['cooking methods', 'nutrition preservation', 'healthy cooking', 'techniques'], true, 0),

-- WELLNESS & LIFESTYLE (6 resources)
('Mindful Eating Practices', 'Transform your relationship with food through awareness.', 'Eat without distractions, chew thoroughly, put utensils down between bites, notice hunger/fullness cues, appreciate food appearance and aroma, eat slowly, recognize emotional vs physical hunger. Benefits: better digestion, reduced overeating, more enjoyment.', 'article', 'wellness', ARRAY['mindful eating', 'mindfulness', 'awareness', 'habits'], true, 0),

('Creating Sustainable Healthy Habits', 'Small changes that lead to lasting transformation.', 'Start small, stack habits, track progress, focus on systems not goals, prepare for obstacles, celebrate wins, be patient with setbacks. Habit formation takes 2-3 months. Focus on one habit at a time. Environment matters - make healthy choices easy.', 'article', 'wellness', ARRAY['habits', 'behavior change', 'goals', 'motivation'], true, 0),

('Exercise and Nutrition Synergy', 'Maximize results by combining movement and nutrition.', 'Exercise increases metabolism, builds muscle, improves insulin sensitivity. Nutrition fuels workouts and recovery. Together: better body composition, energy, mood, disease prevention. Time meals around training. Combine strength training with adequate protein.', 'article', 'exercise', ARRAY['exercise', 'fitness', 'nutrition timing', 'performance'], true, 0),

('Gut-Brain Connection: Nutrition for Mental Health', 'How diet impacts mood, anxiety, and cognitive function.', 'The gut produces 90% of serotonin. Eat: omega-3s (fish), fermented foods (yogurt, kimchi), fiber (vegetables, whole grains), tryptophan (turkey, eggs). Limit sugar and processed foods. Stay hydrated. Regular meals stabilize mood. Consider probiotics.', 'article', 'wellness', ARRAY['gut-brain axis', 'mental health', 'mood', 'brain health'], true, 0),

('Dining Out: Making Healthy Choices', 'Navigate restaurant menus without stress.', 'Preview menus online, ask for modifications, start with salad or soup, choose grilled/baked over fried, request dressing/sauce on side, share dessert, avoid all-you-can-eat, eat slowly, stop when satisfied. Enjoy social experience without derailing goals.', 'article', 'wellness', ARRAY['dining out', 'restaurants', 'social eating', 'meal planning'], true, 0),

('Seasonal Eating: Benefits and Guidelines', 'Align your diet with nature''s rhythms.', 'Seasonal produce: fresher, more nutritious, better taste, lower cost, environmental benefits. Spring: asparagus, peas, strawberries. Summer: tomatoes, corn, berries. Fall: squash, apples, pears. Winter: root vegetables, citrus, dark leafy greens. Shop farmers markets.', 'article', 'nutrition', ARRAY['seasonal eating', 'local food', 'sustainability', 'produce'], true, 0);

-- Success message
SELECT 'Successfully added 56 comprehensive nutrition resources!' as status, COUNT(*) as total_resources FROM educational_resources;
