-- Create Features Table and Seed Data for GreenoFig Platform
-- This migration creates the features table and populates it with all functional features

-- Drop existing table if it exists (use with caution in production)
DROP TABLE IF EXISTS features CASCADE;

-- Create features table
CREATE TABLE features (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    category_icon TEXT NOT NULL DEFAULT 'Heart',
    feature_icon TEXT NOT NULL DEFAULT 'CheckCircle',
    plan_tier TEXT NOT NULL DEFAULT 'Basic',
    is_active BOOLEAN NOT NULL DEFAULT true,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index for faster queries
CREATE INDEX idx_features_category ON features(category);
CREATE INDEX idx_features_plan_tier ON features(plan_tier);
CREATE INDEX idx_features_display_order ON features(display_order);
CREATE INDEX idx_features_is_active ON features(is_active);

-- Enable Row Level Security
ALTER TABLE features ENABLE ROW LEVEL SECURITY;

-- Create policy to allow everyone to read features
CREATE POLICY "Features are viewable by everyone"
    ON features FOR SELECT
    USING (true);

-- Create policy to allow only admins to insert/update/delete features
CREATE POLICY "Only admins can modify features"
    ON features FOR ALL
    USING (
        auth.jwt() ->> 'role' = 'admin' OR
        auth.jwt() ->> 'role' = 'super_admin'
    );

-- NUTRITION & MEAL PLANNING FEATURES
INSERT INTO features (name, description, category, category_icon, feature_icon, plan_tier, is_active, display_order) VALUES
('Quick Log Meals', 'Instantly track your meals with our intuitive meal logging system. Record what you eat throughout the day with nutritional breakdowns.', 'Nutrition & Meal Planning', 'Carrot', 'Utensils', 'Basic', true, 1),
('AI Meal Plan Generator', 'Get personalized meal plans generated by AI based on your dietary preferences, goals, and restrictions. Includes recipes and shopping lists.', 'Nutrition & Meal Planning', 'Carrot', 'Sparkles', 'Premium', true, 2),
('Recipe Database', 'Access thousands of healthy recipes tailored to your dietary needs. Filter by cuisine, preparation time, and ingredients.', 'Nutrition & Meal Planning', 'Carrot', 'BookOpen', 'Premium', true, 3),
('Macro Tracking', 'Track your daily macronutrients (protein, carbs, fats) with detailed breakdowns and progress towards your targets.', 'Nutrition & Meal Planning', 'Carrot', 'PieChart', 'Premium', true, 4),
('Meal Photo Recognition', 'Take a photo of your meal and our AI will automatically identify the food and log the nutrients for you.', 'Nutrition & Meal Planning', 'Carrot', 'Camera', 'Elite', true, 5),
('Custom Meal Plans', 'Work with nutritionists to create fully customized meal plans that fit your unique lifestyle and preferences.', 'Nutrition & Meal Planning', 'Carrot', 'ClipboardEdit', 'Elite', true, 6);

-- FITNESS & WORKOUT FEATURES
INSERT INTO features (name, description, category, category_icon, feature_icon, plan_tier, is_active, display_order) VALUES
('Quick Log Workouts', 'Log your workouts quickly with exercise type, duration, and intensity. Track your fitness journey effortlessly.', 'Fitness & Workouts', 'Dumbbell', 'Activity', 'Basic', true, 10),
('AI Workout Planner', 'Receive personalized workout plans generated by AI that adapt to your fitness level, goals, and available equipment.', 'Fitness & Workouts', 'Dumbbell', 'BrainCircuit', 'Premium', true, 11),
('Exercise Library', 'Access a comprehensive library of exercises with video demonstrations, proper form guides, and muscle group targeting.', 'Fitness & Workouts', 'Dumbbell', 'Video', 'Premium', true, 12),
('Progress Tracking', 'Visualize your fitness progress with detailed charts showing strength gains, endurance improvements, and consistency.', 'Fitness & Workouts', 'Dumbbell', 'TrendingUp', 'Premium', true, 13),
('Workout Analytics', 'Get advanced analytics on your workout performance including volume, intensity, frequency, and recovery metrics.', 'Fitness & Workouts', 'Dumbbell', 'BarChart3', 'Pro', true, 14),
('Wearable Integration', 'Sync data from your Apple Watch, Fitbit, Garmin, and other wearables for automatic workout and activity tracking.', 'Fitness & Workouts', 'Dumbbell', 'Watch', 'Pro', true, 15);

-- HEALTH MONITORING FEATURES
INSERT INTO features (name, description, category, category_icon, feature_icon, plan_tier, is_active, display_order) VALUES
('Quick Log Weight', 'Track your weight daily and see your progress over time with visual graphs and trend analysis.', 'Health Monitoring', 'HeartPulse', 'Scale', 'Basic', true, 20),
('Quick Log Water', 'Monitor your daily water intake to stay hydrated. Set reminders and track your hydration goals.', 'Health Monitoring', 'HeartPulse', 'Droplets', 'Basic', true, 21),
('Quick Log Sleep', 'Record your sleep duration and quality. Understand your sleep patterns and improve your rest.', 'Health Monitoring', 'HeartPulse', 'Moon', 'Basic', true, 22),
('BMI Calculator', 'Calculate and track your Body Mass Index (BMI) to understand your health status and set realistic goals.', 'Health Monitoring', 'HeartPulse', 'Calculator', 'Basic', true, 23),
('Health Streaks', 'Build healthy habits with streak tracking. See how many consecutive days you have logged activities.', 'Health Monitoring', 'HeartPulse', 'Flame', 'Premium', true, 24),
('Personalized Insights', 'Receive AI-powered health insights based on your tracking data, with actionable recommendations for improvement.', 'Health Monitoring', 'HeartPulse', 'Lightbulb', 'Pro', true, 25),
('Advanced Analytics', 'Deep dive into your health data with comprehensive analytics, trends, and predictive insights.', 'Health Monitoring', 'HeartPulse', 'LineChart', 'Pro', true, 26);

-- AI COACHING FEATURES
INSERT INTO features (name, description, category, category_icon, feature_icon, plan_tier, is_active, display_order) VALUES
('24/7 AI Health Coach', 'Chat with your personal AI health coach anytime for motivation, guidance, and answers to your health questions.', 'AI Coaching', 'BrainCircuit', 'MessageSquare', 'Pro', true, 30),
('Personalized Recommendations', 'Get daily personalized recommendations for meals, workouts, and lifestyle adjustments based on your data.', 'AI Coaching', 'BrainCircuit', 'Target', 'Pro', true, 31),
('Goal Setting & Tracking', 'Set SMART goals and let AI help you achieve them with step-by-step guidance and progress monitoring.', 'AI Coaching', 'BrainCircuit', 'Target', 'Premium', true, 32),
('Motivational Support', 'Receive encouraging messages and reminders to keep you on track with your health journey.', 'AI Coaching', 'BrainCircuit', 'Heart', 'Premium', true, 33);

-- PROFESSIONAL SUPPORT FEATURES
INSERT INTO features (name, description, category, category_icon, feature_icon, plan_tier, is_active, display_order) VALUES
('Nutritionist Messaging', 'Connect with certified nutritionists through our secure messaging platform for professional guidance.', 'Professional Support', 'Users', 'Mail', 'Elite', true, 40),
('Doctor Consultations', 'Schedule virtual consultations with licensed doctors for health concerns and medical advice.', 'Professional Support', 'Users', 'Stethoscope', 'Elite', true, 41),
('Appointment Scheduling', 'Book appointments with health professionals directly through the platform with calendar integration.', 'Professional Support', 'Users', 'Calendar', 'Elite', true, 42),
('Priority Support', 'Get priority customer support with faster response times and dedicated account management.', 'Professional Support', 'Users', 'Headphones', 'Elite', true, 43);

-- PLATFORM FEATURES
INSERT INTO features (name, description, category, category_icon, feature_icon, plan_tier, is_active, display_order) VALUES
('Ad-Free Experience', 'Enjoy a clean, distraction-free interface with no advertisements or promotional content.', 'Platform Features', 'Settings', 'EyeOff', 'Premium', true, 50),
('Multi-Device Sync', 'Access your data seamlessly across all your devices with real-time synchronization.', 'Platform Features', 'Settings', 'RefreshCw', 'Premium', true, 51),
('Data Export', 'Export all your health data in standard formats (CSV, PDF, JSON) for your records or external analysis.', 'Platform Features', 'Settings', 'Download', 'Pro', true, 52),
('Dark Mode', 'Protect your eyes with our beautiful dark mode interface, perfect for late-night tracking.', 'Platform Features', 'Settings', 'Moon', 'Basic', true, 53),
('Custom Notifications', 'Set up personalized reminders for meals, workouts, water intake, sleep, and medication.', 'Platform Features', 'Settings', 'Bell', 'Premium', true, 54),
('Progress Reports', 'Receive weekly and monthly progress reports summarizing your achievements and areas for improvement.', 'Platform Features', 'Settings', 'FileText', 'Pro', true, 55),
('Community Features', 'Connect with other users, share your journey, and participate in challenges and group activities.', 'Platform Features', 'Settings', 'Users', 'Elite', true, 56);

-- EDUCATIONAL CONTENT
INSERT INTO features (name, description, category, category_icon, feature_icon, plan_tier, is_active, display_order) VALUES
('Health Blog & Articles', 'Access a library of expert-written articles on nutrition, fitness, mental health, and wellness.', 'Educational Content', 'BookOpen', 'FileText', 'Basic', true, 60),
('Video Tutorials', 'Learn proper exercise form and cooking techniques through our comprehensive video library.', 'Educational Content', 'BookOpen', 'Video', 'Premium', true, 61),
('Webinars & Workshops', 'Attend live webinars with health experts on various wellness topics and get your questions answered.', 'Educational Content', 'BookOpen', 'Presentation', 'Pro', true, 62),
('Nutrition Guides', 'Download comprehensive guides on various diets, supplements, and nutritional strategies.', 'Educational Content', 'BookOpen', 'Download', 'Premium', true, 63);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_features_updated_at
    BEFORE UPDATE ON features
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Verify the insert
SELECT
    category,
    COUNT(*) as feature_count,
    STRING_AGG(DISTINCT plan_tier, ', ' ORDER BY plan_tier) as plans
FROM features
GROUP BY category
ORDER BY MIN(display_order);

-- Show total count
SELECT
    COUNT(*) as total_features,
    COUNT(DISTINCT category) as total_categories,
    COUNT(CASE WHEN plan_tier = 'Basic' THEN 1 END) as basic_features,
    COUNT(CASE WHEN plan_tier = 'Premium' THEN 1 END) as premium_features,
    COUNT(CASE WHEN plan_tier = 'Pro' THEN 1 END) as pro_features,
    COUNT(CASE WHEN plan_tier = 'Elite' THEN 1 END) as elite_features
FROM features;
